dist: trusty
language: rust
services: docker
sudo: required
python: 3.7
env:
  global:
  - CRATE_NAME=checksums
matrix:
  include:
  - env: TARGET=x86_64-unknown-linux-musl
  - env: TARGET=x86_64-apple-darwin
    os: osx
  - env: TARGET=x86_64-pc-windows-gnu
before_install:
- set -e
- rustup self update
install:
- sh ci/install.sh
- source ~/.cargo/env || true
script:
- bash ci/script.sh
after_script: set +e
before_deploy:
- bash ci/before_deploy.sh
deploy:
  api_key:
    secure: t9nwvIIM4HXXwyemT6YfsCseXFAgvhHiNKtrPVZ6tRyxxbOhdPaYz+pq9gkC7R8BFbyliPu/C8Uw5tKhBc48rHHS7F8idfA/sIfgDL02RBx4213mntfI+Hs/Qdgf4MbZG84G5GG1DkRnD50CtWc1HnTa+zFFWhFJy554iqACcXaw7B/m/1qz2dVjYRTZQVtu/WgR8MwV54z/lTxzyZzcTSswyymfx0V5gIYzzXRLmb+NQLNQ3I7XBRYNQxKrZPp/owwEaBMGj4cZNyRWQs3LCqoeV/voHWQJMxI+ktC3ZyUJt36iKcVZC3z1mE706HL4idvDI4Fbou4ITBIhJLdpado20CM1RwEEjqbUdNCB5RcmvUyvclFbOiJvmA2bZ99xLItKonDR33ebTN2SodWbA3j7j5GZ0n+Y/iGtcajXgNPH1lw/OV5PwiZCydOFogwSI5qZ/vVgo/npsPfz5XOl9X4W1OuExeJMbXMzD5sT+CI+L6G/HoFOtmzphu3+VEudFC174GEK5u2E49gvt2xJRGf3uFPPFjEXYUyqZZ+G97HJuuZKXvd8zWtpSuBUjRplSGo/eYRy4yFEElhzbQMugvZyCHWTKXZBpit9B77/UvWspW9NXbSxKFiu6oNw5dybcWMu5+SreWkOPQxdJeU41OV1RVOqMPt0dqjOzIHX9DM=
  file_glob: true
  file: "$CRATE_NAME-$TRAVIS_TAG-$TARGET.*"
  on:
    condition: "$TRAVIS_RUST_VERSION = stable"
    tags: true
  provider: releases
  skip_cleanup: true
cache: cargo
before_cache:
- chmod -R a+r $HOME/.cargo
branches:
  only:
  - "/^v\\d+\\.\\d+\\.\\d+.*$/"
  - master
notifications:
  email:
    on_success: never
